Update erl-dns (use maps for named index)
dcos/spartan pull request #41
Opened 2017-05-16 23:08 UTC by urbanserj

2017-05-23 19:29 UTC, GoelDeepak requested changes

2017-05-23 19:29 UTC, GoelDeepak commented on rebar.config
> +    {erldns, {git, "https://github.com/dcos/erl-dns.git", master}},
Should this follow the recommended style?  {branch, "master"}

2017-05-23 19:44 UTC, urbanserj commented on rebar.config
> +    {erldns, {git, "https://github.com/dcos/erl-dns.git", master}},
Is there recommended style for rebar.config? I tried to use the style from this file. Nobody used `{branch, "master"}` here. Should I change it?

2017-05-23 20:14 UTC, GoelDeepak commented on rebar.config
> +    {erldns, {git, "https://github.com/dcos/erl-dns.git", master}},
yeah, that is a recommendation from rebar.config. We try to change is as and when we update a particular reference. So, yeah it is not complete

2017-05-24 04:14 UTC, GoelDeepak approved these changes

2017-05-24 04:15 UTC, GoelDeepak commented
LGTM

2017-05-25 19:36 UTC, merged