Ensure spartan uses system epmd service
dcos/spartan pull request #44
Opened 2017-05-31 17:56 UTC by urbanserj

Currently it is possible for spartan to start it's own epmd if dcos-epmd is not yet started or has died for some reason. The systemd services for each of the Erlang based components should be reviewed and modified so that each ensures dcos-epmd is already running before starting.

`spartan-env` script is the best place for epmd status check because epmd port has been hardcoded here.

2017-05-31 21:49 UTC, nlsun requested changes
some comments

2017-05-31 21:49 UTC, nlsun commented on bin/spartan-env
> +SCRIPT=$(readlink -f $0 || true)
when would `readlink` fail? is the `|| true` necessary?

2017-05-31 21:49 UTC, nlsun commented on bin/spartan-env
> +[ -z $SCRIPT ] && SCRIPT=$0
instead of having a 2 step, maybe `$readlink -f $0 || echo $0`

2017-05-31 21:49 UTC, nlsun commented on bin/spartan-env
> +RELNAME=${SCRIPT_DIR}/${APP_NAME}
should quote `RELNAME="${SCRIPT_DIR}/${APP_NAME}"`

2017-05-31 21:49 UTC, nlsun commented on bin/spartan-env
> +export ERL_EPMD_PORT=61420
why are we exporting all of these?

2017-05-31 21:49 UTC, nlsun commented on bin/spartan-env
> +export RELEASE_ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"
should use `dirname` instead of `..`

2017-05-31 21:49 UTC, nlsun commented on rebar.config
> +            {template, "bin/spartan-env", "bin/spartan-env"},
Does using this as a template mean that in the `ERTS_VSN="{{ erts_vsn }}"`, `{{ erts_vsn }}` will get filled with the `0.0.1` from
```
{relx, [{release, {spartan, "0.0.1"}, [spartan, erldns, observer, {eper, load}, {runtime_tools, load}, {eflame, load}, {debugger, load}]}
```
?

2017-05-31 22:08 UTC, urbanserj commented on bin/spartan-env
> +SCRIPT=$(readlink -f $0 || true)
I've just copied some code from [relx](https://github.com/erlware/relx/blob/master/priv/templates/extended_bin#L31). I hope they have a reason to do that in this way.

2017-05-31 22:19 UTC, nlsun commented on bin/spartan-env
> +SCRIPT=$(readlink -f $0 || true)
oh, that's fine then

2017-05-31 22:22 UTC, urbanserj commented on rebar.config
> +            {template, "bin/spartan-env", "bin/spartan-env"},
No. `0.0.1` is a spartan version. ERTS version is a version of beam.

```
$ erl
Erlang/OTP 19 [erts-8.3] …
```

2017-05-31 22:23 UTC, urbanserj commented on bin/spartan-env
> +export ERL_EPMD_PORT=61420
I've removed all unnecessary exports from here.

2017-05-31 22:43 UTC, nlsun approved these changes

2017-06-01 17:29 UTC, GoelDeepak approved these changes

2017-06-01 17:47 UTC, drewkerrigan approved these changes
LGTM

2017-06-01 18:08 UTC, merged